"""
Flourish Governed Memory Hub - Cryptographic Audit Ledger Engine (`Stage 5 Engine`)
Matches exactly with Blueprint Sections 26.2 (`AuditChainProtocol`) & 27.1 (`Canonical JSON & HMAC SHA-256`).
Provides $O(1)$ single-row serialized write locking (`SELECT ... FOR UPDATE WHERE lock_key = 1`)
and $O(N)$ sequential chain integrity verification (`verify_integrity`).
"""

import datetime
import hashlib
import hmac
import json
import time
import uuid
from dataclasses import dataclass
from typing import Any, Final, Protocol, runtime_checkable

from sqlalchemy import select
from sqlalchemy.exc import OperationalError

from app.audit.exceptions import (
    AuditConcurrencyError,
    AuditEngineError,
    AuditPayloadValidationError,
    AuditTamperError,
)
from app.core.config import settings
from app.core.constants import AuditActionEnum
from app.models.audit import AuditLog, AuditSequenceHead

# Restricted dictionary keys that must NEVER be stored inside details_json (`RSK-04`)
RESTRICTED_AUDIT_KEYS: Final[set[str]] = {"body", "content", "snippet", "raw_text"}

# Singleton system bootstrap UUID (`ISSUE-LOW-01`)
SYSTEM_BOOTSTRAP_UUID: Final[uuid.UUID] = uuid.UUID("00000000-0000-0000-0000-000000000000")
SYSTEM_BOOTSTRAP_UUID_STR: Final[str] = "00000000-0000-0000-0000-000000000000"


def _canonical_json_default(obj: Any) -> Any:
    """
    Deterministic fallback serializer (`default=...`) for `json.dumps` during canonical payload construction.
    Converts `UUID`, `datetime`, `date`, `set`, and `bytes` into exact, repeatable structures (`ISSUE-MED-01`).
    """
    if isinstance(obj, uuid.UUID):
        return str(obj).lower()
    elif isinstance(obj, datetime.datetime):
        if obj.tzinfo is not None:
            return obj.astimezone(datetime.UTC).isoformat(timespec="microseconds")
        return obj.isoformat(timespec="microseconds")
    elif isinstance(obj, datetime.date):
        return obj.isoformat()
    elif isinstance(obj, (set, frozenset)):
        return sorted(list(obj))
    elif isinstance(obj, bytes):
        return obj.hex()
    raise TypeError(
        f"Object of type {type(obj).__name__} is not JSON serializable for canonical audit payload."
    )


def check_restricted_keys(data: Any, path: str = "details") -> None:
    """
    Recursively inspects data structures (`dict` or `list`) for restricted payload keys (`RSK-04`).
    Raises `AuditPayloadValidationError` instantly if any restricted key (`body`, `content`,
    `snippet`, `raw_text`) is detected at any nesting depth.
    """
    if isinstance(data, dict):
        for k, v in data.items():
            if str(k).lower() in RESTRICTED_AUDIT_KEYS:
                raise AuditPayloadValidationError(
                    f"Restricted key '{k}' detected at '{path}.{k}'. "
                    "Audit ledger cannot store document content, bodies, or unredacted snippets (`RSK-04`)."
                )
            check_restricted_keys(v, f"{path}.{k}")
    elif isinstance(data, list):
        for idx, item in enumerate(data):
            check_restricted_keys(item, f"{path}[{idx}]")


@dataclass(frozen=True)
class AuditEventPayload:
    """
    Payload provided by domain services (`IngestionService`, `GovernanceService`, `RetrievalEngine`)
    when logging an action to the cryptographic audit ledger (`Section 26.2`).
    Enforces frozen immutability and payload validation upon instantiation.
    """

    action_type: str | AuditActionEnum
    actor_id: uuid.UUID | None
    target_id: uuid.UUID | None
    details: dict[str, Any]

    def __post_init__(self) -> None:
        # Validate action_type against AuditActionEnum
        action_val = (
            self.action_type.value
            if isinstance(self.action_type, AuditActionEnum)
            else str(self.action_type)
        )
        try:
            AuditActionEnum(action_val)
        except ValueError as err:
            raise ValueError(f"Invalid action_type '{action_val}' for AuditEventPayload.") from err

        # Perform recursive check on details dictionary (`RSK-04`)
        if self.details:
            check_restricted_keys(self.details)


@dataclass(frozen=True)
class AuditVerifyResult:
    """
    Diagnostic report generated by `verify_integrity()` after sequential $O(N)$ ledger verification (`Section 26.2`).
    """

    compromised: bool
    total_verified: int
    broken_sequence_id: int | None
    reason: str | None
    verification_duration_ms: float


def build_canonical_payload(
    sequence_id: int,
    event_time_iso: str,
    action_type: str,
    actor_id_str: str,
    target_id_str: str,
    details_dict: dict[str, Any],
    prev_hash_hex: str,
) -> str:
    """
    Produces the exact canonical UTF-8 string required for HMAC SHA-256 signing (`Section 27.1`).
    Rules:
      1. Key sorting: sort_keys=True
      2. Compact separators: separators=(',', ':')
      3. Unicode preservation: ensure_ascii=False
      4. Exact 7-part pipe delimitation: seq|time|action|actor|target|details_canonical|prev_hash
    """
    details_canonical = json.dumps(
        details_dict or {},
        sort_keys=True,
        separators=(",", ":"),
        ensure_ascii=False,
        default=_canonical_json_default,
    )
    return (
        f"{sequence_id}|{event_time_iso}|{action_type}|{actor_id_str}|"
        f"{target_id_str}|{details_canonical}|{prev_hash_hex}"
    )


def compute_hmac_sha256(secret_key: bytes, canonical_payload: str) -> str:
    """
    Returns a lowercase 64-character hexadecimal HMAC SHA-256 signature (`Section 27.1`).
    Raises `AuditEngineError` if secret_key is missing or empty.
    """
    if not secret_key or len(secret_key) < 1:
        raise AuditEngineError(
            "Insecure or missing AUDIT_HMAC_SECRET for HMAC SHA-256 computation."
        )
    return (
        hmac.new(
            secret_key,
            canonical_payload.encode("utf-8"),
            hashlib.sha256,
        )
        .hexdigest()
        .lower()
    )


@runtime_checkable
class AuditChainProtocol(Protocol):
    """
    Contract for append-only cryptographic HMAC-SHA256 hash chaining and verification (`Section 26.2`).
    Operates asynchronously over an open SQLAlchemy AsyncSession.
    """

    async def log_event(self, session: Any, payload: AuditEventPayload) -> int:
        """
        Acquires row lock on audit_sequence_head (`lock_key = 1`), computes HMAC SHA-256 hash,
        appends to audit_logs, and updates head. Returns newly inserted sequence_id.
        """
        ...

    async def verify_integrity(self, session: Any, secret_key: bytes) -> AuditVerifyResult:
        """Sequential $O(N)$ verification of all audit log rows against server secret key."""
        ...


class AuditChainService:
    """
    Concrete implementation of `AuditChainProtocol` (`Section 26.2 & Section 27.1`).
    Ensures $O(1)$ single-row concurrency serialization (`RSK-01`) and tamper-evident append chaining.
    """

    def __init__(self, secret_key: bytes | None = None) -> None:
        self._secret_key: bytes = (
            secret_key if secret_key is not None else settings.AUDIT_HMAC_SECRET.encode("utf-8")
        )

    async def log_event(self, session: Any, payload: AuditEventPayload) -> int:
        """
        Appends a new cryptographic event to `audit_logs` within the caller's shared transaction boundary (`Section 15`).
        Uses `SELECT ... FOR UPDATE WHERE lock_key = 1` on `audit_sequence_head` (`RSK-01`).
        """
        # Ensure payload details are validated (`RSK-04`)
        if payload.details:
            check_restricted_keys(payload.details)

        # 1. Acquire single-row serialization lock on audit_sequence_head (`lock_key = 1`)
        stmt = select(AuditSequenceHead).where(AuditSequenceHead.lock_key == 1).with_for_update()
        try:
            result = await session.execute(stmt)
            head_row = result.scalar_one_or_none()
        except OperationalError as err:
            raise AuditConcurrencyError(
                "Lock timeout or deadlock while acquiring exclusive lock on audit_sequence_head (`RSK-01`)."
            ) from err

        if head_row is None:
            raise AuditTamperError(
                "Singleton audit sequence head (`lock_key = 1`) missing or corrupted. "
                "System integrity compromised (`RSK-01`)."
            )

        # 2. Compute sequence advancement & time
        next_seq = head_row.last_sequence_id + 1
        prev_hash = head_row.last_entry_hash

        if head_row.last_sequence_id == 0 and prev_hash != ("0" * 64):
            raise AuditTamperError("Corrupted initial audit sequence head prev_hash pointer.")

        event_time = datetime.datetime.now(datetime.UTC)
        # Ensure exact microsecond precision (`timespec='microseconds'`) for byte-level determinism
        event_time_iso = event_time.astimezone(datetime.UTC).isoformat(timespec="microseconds")

        # 3. Normalize strings for canonical payload (`ISSUE-LOW-01`)
        action_type_str = (
            payload.action_type.value
            if isinstance(payload.action_type, AuditActionEnum)
            else str(payload.action_type)
        )
        actor_str = (
            str(payload.actor_id).lower()
            if payload.actor_id is not None and payload.actor_id != SYSTEM_BOOTSTRAP_UUID
            else "SYSTEM"
        )
        target_str = str(payload.target_id).lower() if payload.target_id is not None else "NONE"

        canonical_str = build_canonical_payload(
            sequence_id=next_seq,
            event_time_iso=event_time_iso,
            action_type=action_type_str,
            actor_id_str=actor_str,
            target_id_str=target_str,
            details_dict=payload.details or {},
            prev_hash_hex=prev_hash,
        )

        # 4. Compute HMAC SHA-256 digest (`Section 27.1`)
        entry_hash = compute_hmac_sha256(self._secret_key, canonical_str)

        action_enum_val = (
            payload.action_type
            if isinstance(payload.action_type, AuditActionEnum)
            else AuditActionEnum(action_type_str)
        )

        # Map null actor_id (`SYSTEM`) to all-zeros UUID for physical database FK safety
        db_actor_id = payload.actor_id if payload.actor_id is not None else SYSTEM_BOOTSTRAP_UUID

        new_log = AuditLog(
            sequence_id=next_seq,
            event_time=event_time,
            action_type=action_enum_val,
            actor_id=db_actor_id,
            target_id=payload.target_id,
            details_json=payload.details or {},
            prev_hash=prev_hash,
            entry_hash=entry_hash,
        )

        # 5. Append row and update sequence head pointer atomically inside shared transaction boundary
        session.add(new_log)
        head_row.last_sequence_id = next_seq
        head_row.last_entry_hash = entry_hash

        await session.flush()
        return int(next_seq)

    async def verify_integrity(
        self, session: Any, secret_key: bytes | None = None
    ) -> AuditVerifyResult:
        """
        Performs sequential $O(N)$ verification of all audit log rows against the server secret key (`Section 26.2`).
        Uses streaming selection to maintain $O(1)$ memory consumption regardless of ledger volume.
        """
        key = secret_key if secret_key is not None else self._secret_key
        start_time = time.perf_counter()

        expected_prev_hash = "0" * 64
        total_verified = 0

        # Option C: Snapshot the expected head state first to prevent READ COMMITTED false positives
        head_stmt = select(AuditSequenceHead).where(AuditSequenceHead.lock_key == 1)
        head_res = await session.execute(head_stmt)
        head_row = head_res.scalar_one_or_none()

        if head_row is None:
            return AuditVerifyResult(
                compromised=True,
                total_verified=0,
                broken_sequence_id=None,
                reason="System Integrity Compromised: AuditSequenceHead lock is missing.",
                verification_duration_ms=0.0,
            )

        expected_seq = head_row.last_sequence_id
        expected_final_hash = head_row.last_entry_hash

        # Execute unshared read-only streaming query ordered strictly by sequence_id (`ISSUE-LOW-02`)
        stmt = select(AuditLog).order_by(AuditLog.sequence_id.asc())
        stream = await session.stream(stmt)

        try:
            async for row_tuple in stream:
                row: AuditLog = row_tuple[0]

                # Optimistic Read-Order: Ignore concurrent appends safely without blocking ingestion
                if row.sequence_id > expected_seq:
                    break

                total_verified += 1

                # 1. Verify hash chain link (`prev_hash`)
                if row.prev_hash != expected_prev_hash:
                    duration_ms = (time.perf_counter() - start_time) * 1000.0
                    return AuditVerifyResult(
                        compromised=True,
                        total_verified=total_verified,
                        broken_sequence_id=row.sequence_id,
                        reason=(
                            f"Broken Chain Link at sequence {row.sequence_id}: "
                            f"expected prev_hash '{expected_prev_hash}', got '{row.prev_hash}'"
                        ),
                        verification_duration_ms=duration_ms,
                    )

                # 2. Reconstruct canonical string (`ISSUE-LOW-01`)
                event_time_iso = row.event_time.astimezone(datetime.UTC).isoformat(
                    timespec="microseconds"
                )
                action_str = (
                    row.action_type.value
                    if isinstance(row.action_type, AuditActionEnum)
                    else str(row.action_type)
                )
                actor_str = (
                    str(row.actor_id).lower()
                    if row.actor_id and str(row.actor_id).lower() != SYSTEM_BOOTSTRAP_UUID_STR
                    else "SYSTEM"
                )
                target_str = str(row.target_id).lower() if row.target_id is not None else "NONE"

                canonical_str = build_canonical_payload(
                    sequence_id=row.sequence_id,
                    event_time_iso=event_time_iso,
                    action_type=action_str,
                    actor_id_str=actor_str,
                    target_id_str=target_str,
                    details_dict=row.details_json or {},
                    prev_hash_hex=row.prev_hash,
                )

                # 3. Recompute HMAC digest and verify exact match
                computed_hash = compute_hmac_sha256(key, canonical_str)
                if computed_hash != row.entry_hash:
                    duration_ms = (time.perf_counter() - start_time) * 1000.0
                    return AuditVerifyResult(
                        compromised=True,
                        total_verified=total_verified,
                        broken_sequence_id=row.sequence_id,
                        reason=(
                            f"Signature Mismatch at sequence {row.sequence_id}: "
                            "HMAC digest verification failed"
                        ),
                        verification_duration_ms=duration_ms,
                    )

                # 4. Advance expected pointer
                expected_prev_hash = row.entry_hash

            # 5. Option C Post-Loop Assertions to mathematically catch tail truncation
            if total_verified == 0 and expected_seq > 0:
                duration_ms = (time.perf_counter() - start_time) * 1000.0
                return AuditVerifyResult(
                    compromised=True,
                    total_verified=0,
                    broken_sequence_id=None,
                    reason=f"Ledger Truncated: expected {expected_seq} sequences, but found none.",
                    verification_duration_ms=duration_ms,
                )

            if total_verified < expected_seq:
                duration_ms = (time.perf_counter() - start_time) * 1000.0
                return AuditVerifyResult(
                    compromised=True,
                    total_verified=total_verified,
                    broken_sequence_id=None,
                    reason=f"Ledger Truncated: expected {expected_seq} sequences, but stream ended at {total_verified}.",
                    verification_duration_ms=duration_ms,
                )

            if expected_prev_hash != expected_final_hash and expected_seq > 0:
                duration_ms = (time.perf_counter() - start_time) * 1000.0
                return AuditVerifyResult(
                    compromised=True,
                    total_verified=total_verified,
                    broken_sequence_id=total_verified,
                    reason=f"Ledger Tail Corrupted: final entry hash '{expected_prev_hash}' does not match head '{expected_final_hash}'.",
                    verification_duration_ms=duration_ms,
                )

            duration_ms = (time.perf_counter() - start_time) * 1000.0
            return AuditVerifyResult(
                compromised=False,
                total_verified=total_verified,
                broken_sequence_id=None,
                reason="Integrity verified: all cryptographic HMAC signatures and chain links intact.",
                verification_duration_ms=duration_ms,
            )
        finally:
            await stream.close()


__all__ = [
    "AuditEventPayload",
    "AuditVerifyResult",
    "AuditChainProtocol",
    "AuditChainService",
    "build_canonical_payload",
    "compute_hmac_sha256",
    "check_restricted_keys",
    "RESTRICTED_AUDIT_KEYS",
    "SYSTEM_BOOTSTRAP_UUID",
    "_canonical_json_default",
]
